### PR TITLE
Fix Project files

### PR DESCRIPTION
**Pull request by Tokazama**
I completely forgot to check dependencies on the last PR. This also sets the test dependencies more appropriately.

### CODE REVIEW

**Comment by Tokazama** [comment]
Looks like I'm hitting problems with Julia 1.0 not supporting the new test files format. It might be fine to just test 1.4+ from now on given Julia should have a new LTS soon.

**Comment by Tokazama** [comment]
I'll leave this open for one more day in case anyone wants to comment. It basically will mean that NIfTI.jl doesn't officially test/support anything pre-1.4.

**Comment by korbinian90** [comment]
I think it's good to drop the dependency to `Test`, but I'm not sure if it's worth to lose v1.0 testing.

As I understand it, the package would be still compatible with v1.0, just not tested and thus not officially supported. So it would be easy that v1.0 incompatibilities sneak in to the "stable Julia v1.0 LTS" environment. Forcing the compatibilty to a higher Julia version on the other hand would then require for all packages building on NIfTI.jl to drop v1.0 support.

I think the [Julia pre-1.2 approach](https://julialang.github.io/Pkg.jl/v1/creating-packages/#Test-specific-dependencies-in-Julia-1.0-and-1.1-1) would be a good option: with `[extras]` and `[targets]` in the Project.toml
If you have both test configurations, all >1.2 versions use the newer `test/Project.toml` file and pre-1.2 uses the old approach. The only disadvantage would be to keep test dependencies updated in both places.

I copied your pull request (without the last commit) and tried it there (Travis test is passing for Julia v1.0):

https://github.com/korbinian90/NIfTI.jl/commit/666bc40c4637ca4e84911bed01e951b93e7c9c0a

**Comment by Tokazama** [comment]
I think that Julia 1.6 will be the next LTS and TBH a lot of stuff that I plan to incorporate soon will be pretty difficult to ensure compatibility with anything before 1.3. In other words, ensuring compatibility with v1.0 is unlikely to make a difference once new features are added.

That being said, I'd be open to supporting the pre v1.2 test stuff in the Project.toml if it really is helping anyone for the time being.

**Pull request merged**
