### PR TITLE
Deprecations and not passing tests

### PR DESCRIPTION
**Pull request by AShedko**
Added v0.6 compat.
* fixed deprecations
* fixed test not passing

since https://nifti.nimh.nih.gov/nifti-1/data/avg152T1_LR_nifti.nii.gz is down i commented that out

### CODE REVIEW

**Comment by timholy** [comment]
Seems OK to me. @simonster, I assume you're OK with this.

**Comment by AShedko** [comment]
Just as an aside: what`s wrong with tests on nightly?

**Comment by timholy** [comment]
You've got a space problem in your comprehension on line 19. Interesting this was only picked up by nightly, though.

**Comment by AShedko** [comment]
Right, thanks. Is Mmap being removed?

**Comment by timholy** [comment]
It's now in the std library:

> WARNING: Base.Mmap is deprecated, run `using Mmap` instead.

**Comment by AShedko** [comment]
I`m currenly running source-built 0.6 so I didn`t know.
Fixed Mmap for 0.7+

**Comment by AShedko** [comment]
Hurray for build passing ?!

**Comment by timholy** [comment]
Hurray for nice people who fix things! :smile:

**Comment by timholy** [comment]
New release tagged.

**Pull request merged**
